services:
  db:
    image: postgres # Or another desired version like postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
