name: otel
services:
  opentelemetry-collector-contrib:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 4317:4317
      - 4318:4318
